
import { GoogleGenAI, Type } from "@google/genai";
import { VisualSummary } from "../types";

/**
 * Generates a structured summary for the card UI using Gemini 3 Flash.
 * This function follows the latest @google/genai guidelines for JSON output.
 */
export const generateVisualSummary = async (html: string, subject: string): Promise<VisualSummary> => {
  // Always use const ai = new GoogleGenAI({apiKey: process.env.API_KEY});
  // Create a new GoogleGenAI instance right before making an API call.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Analyze this email (Subject: ${subject}) and extract a clean, professional visual summary. 
    Email HTML/Text: ${html.substring(0, 5000)}`,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          headline: { type: Type.STRING, description: "A catchy short headline for the email" },
          senderName: { type: Type.STRING, description: "The professional name of the sender" },
          summary: { type: Type.STRING, description: "A 1-2 sentence high-level summary" },
          bulletPoints: { type: Type.ARRAY, items: { type: Type.STRING }, description: "3-4 key points from the email" },
          themeColor: { type: Type.STRING, description: "A hex color code that fits the brand" },
          callToAction: { type: Type.STRING, description: "Optional call to action text" }
        },
        propertyOrdering: ["headline", "senderName", "summary", "bulletPoints", "themeColor", "callToAction"],
        required: ["headline", "senderName", "summary", "bulletPoints", "themeColor"]
      }
    }
  });

  // Use the .text property directly as per guidelines (not .text())
  const text = response.text;
  if (!text) throw new Error("AI Summary failed to generate a response.");
  
  try {
    return JSON.parse(text.trim());
  } catch (error) {
    console.error("Failed to parse Gemini JSON response:", text);
    throw new Error("Invalid response format from AI service.");
  }
};

/**
 * Generates a literal PNG image using Gemini 2.5 Flash Image.
 * This is used for generating shared assets directly within the bridge.
 */
export const generateVisualImage = async (subject: string, body: string): Promise<string> => {
  // Always use const ai = new GoogleGenAI({apiKey: process.env.API_KEY});
  // Create a new GoogleGenAI instance right before making an API call.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const prompt = `Create a professional, high-resolution infographic-style summary card for an email.
  Subject: ${subject}
  Content: ${body.substring(0, 1000)}
  
  Style Requirements:
  - Background: Clean white or very light gray.
  - Layout: Headline at top, followed by 3 key bullet points.
  - Branding: Modern, flat design, professional typography.
  - Colors: Use a professional blue or green accent color.
  - Format: A vertical card suitable for WhatsApp sharing.
  - Include a small "Generated by WA Bridge" watermark at the very bottom.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts: [{ text: prompt }] },
    config: {
      imageConfig: {
        aspectRatio: "9:16"
      }
    }
  });

  // Iterate through all parts to find the image part as per guidelines
  if (response.candidates && response.candidates[0].content.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64EncodeString: string = part.inlineData.data;
        return `data:image/png;base64,${base64EncodeString}`;
      } else if (part.text) {
        console.debug("Model response text:", part.text);
      }
    }
  }
  
  throw new Error("No image data was returned by the model.");
};
