
import { GoogleGenAI, Type } from "@google/genai";
import { VisualSummary } from "../types";

const getAiClient = () => {
  const apiKey = typeof process !== 'undefined' && process.env ? process.env.API_KEY : '';
  return new GoogleGenAI({ apiKey: apiKey || '' });
};

/**
 * Generates a structured summary for the card UI
 */
export const generateVisualSummary = async (html: string, subject: string): Promise<VisualSummary> => {
  const ai = getAiClient();
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Analyze this email (Subject: ${subject}) and extract a clean, professional visual summary. 
    Email HTML/Text: ${html.substring(0, 5000)}`,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          headline: { type: Type.STRING },
          senderName: { type: Type.STRING },
          summary: { type: Type.STRING },
          bulletPoints: { type: Type.ARRAY, items: { type: Type.STRING } },
          themeColor: { type: Type.STRING },
          callToAction: { type: Type.STRING }
        },
        required: ["headline", "senderName", "summary", "bulletPoints", "themeColor"]
      }
    }
  });

  if (!response.text) throw new Error("AI Summary failed");
  return JSON.parse(response.text.trim());
};

/**
 * Generates a literal PNG image using Gemini 2.5 Flash Image.
 * This is used for the "In-Addon" experience where no browser tab can be opened.
 */
export const generateVisualImage = async (subject: string, body: string): Promise<string> => {
  const ai = getAiClient();
  const prompt = `Create a professional, high-resolution infographic-style summary card for an email.
  Subject: ${subject}
  Content: ${body.substring(0, 1000)}
  
  Style Requirements:
  - Background: Clean white or very light gray.
  - Layout: Headline at top, followed by 3 key bullet points.
  - Branding: Modern, flat design, professional typography.
  - Colors: Use a professional blue or green accent color.
  - Format: A vertical card suitable for WhatsApp sharing.
  - Include a small "Generated by WA Bridge" watermark at the very bottom.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: [{ parts: [{ text: prompt }] }],
    config: {
      imageConfig: {
        aspectRatio: "9:16"
      }
    }
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image part returned from Gemini");
};
